apiVersion: v1
kind: Service
metadata:
  labels:
    app: discover
  name: ratingdb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: discover
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingdb
  labels:
    app: discover
spec:
  selector:
    matchLabels:
      app: discover
  replicas: 1
  template:
    metadata:
      labels:
        app: discover
      name: ratingdb-service


    spec:
      containers:
        - image: mongo:latest
          name: ratingdb

          ports:
            - containerPort: 27017
              name: ratingdb