apiVersion: v1
kind: Service
metadata:
  name: userrating-service
spec:
  type: NodePort
  selector:
    app: discover
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000