apiVersion: v1
kind: Service
metadata:
  name: car-catalog-service
spec:
  type: NodePort
  selector:
    app: discover
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 31000