apiVersion: v1
kind: Service
metadata:
  name: discover-service
spec:
  type: NodePort
  selector:
    app: discover
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30000